//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coustomer()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int CoutomerID { get; set; }
        public string CoustomerName { get; set; }
        public string CoustomerTell { get; set; }
        public string CoustoemrAddres { get; set; }
        public string SetDate { get; set; }
        public int UserID { get; set; }
        public string UpdateDate { get; set; }
        public Nullable<byte> CoustomerActive { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
