//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public int UserAccessID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SystemPartID { get; set; }
    
        public virtual SystemPart SystemPart { get; set; }
        public virtual User User { get; set; }
    }
}
