//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_InvoiceItem
    {
        public int InvoceItemID { get; set; }
        public int InvoceItemCount { get; set; }
        public int InvoiceID { get; set; }
        public long InvoceItemFeePurche { get; set; }
        public long InvoceItemFeeSell { get; set; }
        public int ProudactID { get; set; }
        public string ProductName { get; set; }
        public string UserName { get; set; }
        public string UserFamily { get; set; }
        public string FullName { get; set; }
    }
}
