//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_InvoiceShow
    {
        public string InvoiceDate { get; set; }
        public Nullable<long> InvoicePrice { get; set; }
        public string InvocieDesc { get; set; }
        public Nullable<byte> InvoiceType { get; set; }
        public int UserID { get; set; }
        public int CoustoemrId { get; set; }
        public Nullable<long> InvocePrice_Pourche { get; set; }
        public int InvoiceId { get; set; }
        public string CoustomerName { get; set; }
        public string CoustomerTell { get; set; }
        public string CoustoemrAddres { get; set; }
        public string UserName { get; set; }
        public string UserFamily { get; set; }
        public string FullName { get; set; }
        public string InvoceTypeFarsi { get; set; }
    }
}
