//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Inventory
    {
        public int InventoryID { get; set; }
        public int InventoryCount { get; set; }
        public string InventoryDate { get; set; }
        public string InventoryDesc { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserFamily { get; set; }
        public string ProductName { get; set; }
        public string FullName { get; set; }
        public string Stutus { get; set; }
        public int ProductID { get; set; }
    }
}
